// Generated by dts-bundle-generator v9.5.1

declare const SURFY_SDK_ERROR_CODES: readonly [
	"AUTH_EXPIRED",
	"AUTH_FORBIDDEN",
	"TENANT_MISMATCH",
	"LAYOUT_NOT_FOUND",
	"NETWORK",
	"SDK_CONFIG",
	"PIN_GPS_UNAVAILABLE"
];
export type SurfySdkErrorCode = (typeof SURFY_SDK_ERROR_CODES)[number];
export interface SurfySdkErrorDetail {
	readonly code: SurfySdkErrorCode;
	readonly message: string;
}
export interface IPaginationList<T> {
	totalCount?: number;
	entities?: T[];
}
export type IconStyle = "solid" | "regular" | "light" | "thin" | "duotone" | "brands";
export type FontAwesomeIconsStyle = IconStyle;
export type IconShapeType = "circle" | "rectangle" | "triangle";
export type DaySlotType = "am" | "pm" | "all" | "custom";
export type ParkingRoomTypeCode = "PARKING-CAR" | "PARKING-ELECTRIC-CAR" | "PARKING-PRM" | "PARKING-MOTO";
export interface ICustomIconProperties {
	defaultBorderColor?: string;
	defaultBackgroundColor?: string;
	defaultColor?: string;
	defaultShape?: IconShapeType;
}
export interface ICustomIcon extends ICustomIconProperties {
	name: string;
	unicode: string;
}
export type JupIconSet = "fontawesome" | "material-ui" | "surfy" | "icomoon";
export type JupIconSyle = FontAwesomeIconsStyle | "surfyicon" | "icomoon";
export interface IJupIcon extends ICustomIcon {
	style: JupIconSyle;
	set: JupIconSet;
}
export interface ITextAnchor {
	textPosition: IPoint3d;
	anchorPosition: IPoint3d;
	displayLine: boolean;
}
export interface IJupTransform {
	translate: IPoint2d;
	rotate: number;
	scale: number;
}
export interface IPoint2d {
	x: number;
	y: number;
}
export interface IPoint3d extends IPoint2d {
	z: number;
}
export interface ISize {
	width: number;
	height: number;
}
export interface IJupImage {
	url: string;
	phash: string | null;
	size: ISize;
}
export interface IModel3d {
	url: string;
}
/**
 * Structured address with detailed components
 * Matches Microsoft Places API address format
 */
export interface IJupAddressStructured {
	street?: string;
	city?: string;
	state?: string;
	postalCode?: string;
	countryOrRegion?: string;
	countryOrRegionIsoCode?: string;
}
export interface IJupAddress {
	address: string;
	lat: number;
	lng: number;
	structured?: IJupAddressStructured;
}
export interface IJupLegendConfiguration {
	properties: string[];
}
/** Optional vertical label strip on the right side of item-type icons (extinguisher variants, etc.). */
export interface IItemTypeIconBadge {
	text: string;
	backgroundColor: string;
	textColor: string;
}
export interface IGridNodeLink {
	difficulty: number;
	nodeId: string;
}
export type GridNodeType = "edge" | "edge-merged" | "grid" | "merged";
export interface IGridNode {
	point: IPoint2d;
	id: string;
	nexts: IGridNodeLink[];
	previous: IGridNodeLink[];
	type: GridNodeType;
	roomIds: number[];
	options: IGridNodeOptions;
	floorId: number;
}
export interface IGridNodeOptions {
	groupSize?: number;
}
export interface IFloorPathfindingGraph {
	mergedNodes: IGridNode[];
}
export interface IEntity {
	id: number;
}
export interface ICompanyTypeRaw extends IEntity {
	id: number;
	name: string;
	billable?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface ICompanyType extends ICompanyTypeRaw {
	companies?: IPaginationList<ICompany>;
}
export interface IContentRoleToBuildingRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	contentRoleId: number;
	buildingId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IContentRoleToBuilding extends IContentRoleToBuildingRaw {
	contentRole?: IContentRole;
	building?: IBuilding;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface ICostCenterBuildingRaw extends IEntity {
	id: number;
	roomsArea: number;
	roomsCount: number;
	workplacesCount: number;
	workplacesRatio: number;
	peopleCount: number;
	seatsCount: number;
	peopleRatio: number;
	occupancyRate: number;
	expansionRatio: number;
	freeWorkplacesCount: number;
	flexWorkplacesCount: number;
	sharedWorkplacesCount: number;
	sharedWorkplacesRatio: number;
	transitWorkplacesCount: number;
	flexRatio: number;
	seatsPeopleRatio: number;
	totalPeopleCount: number;
	carbonFootprint: number;
	totalCapacityCount: number;
	totalCapacityWorkplaceCountRatio: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	costCenterId: number;
	buildingId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface ICostCenterBuilding extends ICostCenterBuildingRaw {
	costCenter?: ICostCenter;
	building?: IBuilding;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IDimensionFloorRaw extends IEntity {
	id: number;
	bookableWorkplacesCount?: number;
	roomsArea: number;
	roomsCount: number;
	workplacesCount: number;
	workplacesRatio: number;
	peopleCount: number;
	seatsCount: number;
	peopleRatio: number;
	occupancyRate: number;
	expansionRatio: number;
	freeWorkplacesCount: number;
	flexWorkplacesCount: number;
	sharedWorkplacesCount: number;
	sharedWorkplacesRatio: number;
	transitWorkplacesCount: number;
	flexRatio: number;
	seatsPeopleRatio: number;
	totalPeopleCount: number;
	carbonFootprint: number;
	totalCapacityCount: number;
	totalCapacityWorkplaceCountRatio: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	dimensionId?: number | null;
	dimensionTypeId: number;
	floorId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IDimensionFloor extends IDimensionFloorRaw {
	dimension?: IDimension;
	dimensionType?: IDimensionType;
	floor?: IFloor;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IPartnerExportMappingConfigurationToFloorRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	partnerExportMappingConfigurationId: number;
	floorId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPartnerExportMappingConfigurationToFloor extends IPartnerExportMappingConfigurationToFloorRaw {
	partnerExportMappingConfiguration?: IPartnerExportMappingConfiguration;
	floor?: IFloor;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IPartnerExportMappingConfigurationRaw extends IEntity {
	id: number;
	code: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPartnerExportMappingConfiguration extends IPartnerExportMappingConfigurationRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	partnerExportMappings?: IPaginationList<IPartnerExportMapping>;
	partnerExportMappingConfigurationToFloors?: IPaginationList<IPartnerExportMappingConfigurationToFloor>;
}
export interface IPartnerExportMappingRaw extends IEntity {
	id: number;
	partnerCode: string;
	label?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	partnerExportMappingConfigurationId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPartnerExportMapping extends IPartnerExportMappingRaw {
	partnerExportMappingConfiguration?: IPartnerExportMappingConfiguration;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	partnerExportMappingToRoomTypes?: IPaginationList<IPartnerExportMappingToRoomType>;
}
export interface IPartnerExportMappingToRoomTypeRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	partnerExportMappingId: number;
	roomTypeId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPartnerExportMappingToRoomType extends IPartnerExportMappingToRoomTypeRaw {
	partnerExportMapping?: IPartnerExportMapping;
	roomType?: IRoomType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IItemFactRaw extends IEntity {
	id: number;
	measure?: string;
	value: number;
	voltage?: number;
	time?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	itemId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IItemFact extends IItemFactRaw {
	item?: IItem;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IItemToPersonRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personId: number;
	itemId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IItemToPerson extends IItemToPersonRaw {
	person?: IPerson;
	item?: IItem;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IItemTypeFamilyRaw extends IEntity {
	id: number;
	name: string;
	code?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IItemTypeFamily extends IItemTypeFamilyRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	itemTypes?: IPaginationList<IItemType>;
}
export interface IItemTypeVisualEdgeRaw extends IEntity {
	id: number;
	x1: number;
	y1: number;
	x2: number;
	y2: number;
	sortIndex: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	itemTypeId: number;
	itemTypePointStartId?: number | null;
	itemTypePointEndId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IItemTypeVisualEdge extends IItemTypeVisualEdgeRaw {
	itemType?: IItemType;
	itemTypePointStart?: IItemTypePoint;
	itemTypePointEnd?: IItemTypePoint;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IItemTypePointRaw extends IEntity {
	id: number;
	x: number;
	y: number;
	sortIndex: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	itemTypeId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IItemTypePoint extends IItemTypePointRaw {
	itemType?: IItemType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	itemTypeVisualEdgeStarts?: IPaginationList<IItemTypeVisualEdge>;
	itemTypeVisualEdgeEnds?: IPaginationList<IItemTypeVisualEdge>;
}
export interface IManufacturerRaw extends IEntity {
	id: number;
	name: string;
	website?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IManufacturer extends IManufacturerRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	itemTypes?: IPaginationList<IItemType>;
}
export interface IObject3dModelRaw extends IEntity {
	id: number;
	name: string;
	type: string;
	rotation: number;
	origin: string;
	model: IModel3d;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IObject3dModel extends IObject3dModelRaw {
	itemTypes?: IPaginationList<IItemType>;
}
export interface IPersonCompanyMissionRaw extends IEntity {
	id: number;
	name: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IPersonCompanyMission extends IPersonCompanyMissionRaw {
	personCompanyToItemTypes?: IPaginationList<IPersonCompanyToItemType>;
	personCompanyToRoomTypes?: IPaginationList<IPersonCompanyToRoomType>;
}
export interface IPersonCompanyToItemTypeRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personCompanyId: number;
	itemTypeId: number;
	personCompanyMissionId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonCompanyToItemType extends IPersonCompanyToItemTypeRaw {
	personCompany?: IPersonCompany;
	itemType?: IItemType;
	personCompanyMission?: IPersonCompanyMission;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IOrganizationBuildingRaw extends IEntity {
	id: number;
	roomsArea: number;
	roomsCount: number;
	workplacesCount: number;
	workplacesRatio: number;
	peopleCount: number;
	seatsCount: number;
	peopleRatio: number;
	occupancyRate: number;
	expansionRatio: number;
	freeWorkplacesCount: number;
	flexWorkplacesCount: number;
	sharedWorkplacesCount: number;
	sharedWorkplacesRatio: number;
	transitWorkplacesCount: number;
	flexRatio: number;
	seatsPeopleRatio: number;
	totalPeopleCount: number;
	carbonFootprint: number;
	totalCapacityCount: number;
	totalCapacityWorkplaceCountRatio: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	organizationId: number;
	buildingId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IOrganizationBuilding extends IOrganizationBuildingRaw {
	organization?: IOrganization;
	building?: IBuilding;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IOrganizationFloorRaw extends IEntity {
	id: number;
	roomsArea: number;
	roomsCount: number;
	workplacesCount: number;
	workplacesRatio: number;
	peopleCount: number;
	seatsCount: number;
	peopleRatio: number;
	occupancyRate: number;
	expansionRatio: number;
	freeWorkplacesCount: number;
	flexWorkplacesCount: number;
	sharedWorkplacesCount: number;
	sharedWorkplacesRatio: number;
	transitWorkplacesCount: number;
	flexRatio: number;
	seatsPeopleRatio: number;
	totalPeopleCount: number;
	carbonFootprint: number;
	totalCapacityCount: number;
	totalCapacityWorkplaceCountRatio: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	organizationId: number;
	floorId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IOrganizationFloor extends IOrganizationFloorRaw {
	organization?: IOrganization;
	floor?: IFloor;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IOrganizationRaw extends IEntity {
	id: number;
	name: string;
	code?: string;
	color?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	organizationId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IOrganization extends IOrganizationRaw {
	organization?: IOrganization;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	organizations?: IPaginationList<IOrganization>;
	rooms?: IPaginationList<IRoom>;
	people?: IPaginationList<IPerson>;
	workplaces?: IPaginationList<IWorkplace>;
	organizationFloors?: IPaginationList<IOrganizationFloor>;
	organizationBuildings?: IPaginationList<IOrganizationBuilding>;
}
export interface IPersonToDimensionBookingRaw extends IEntity {
	id: number;
	startDatetime: string;
	endDatetime: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personId: number;
	dimensionId: number;
	personWorkingLocationId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonToDimensionBooking extends IPersonToDimensionBookingRaw {
	person?: IPerson;
	dimension?: IDimension;
	personWorkingLocation?: IPersonWorkingLocation;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IPersonToRoomBookingRaw extends IEntity {
	id: number;
	startDatetime: string;
	endDatetime: string;
	roomHasBeenConfirmedAt?: string;
	emailConfirmationWarningNotificationSentAt?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personId: number;
	roomId: number;
	personWorkingLocationId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonToRoomBooking extends IPersonToRoomBookingRaw {
	person?: IPerson;
	room?: IRoom;
	personWorkingLocation?: IPersonWorkingLocation;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IWorkingLocationRaw extends IEntity {
	id: number;
	name: string;
	code: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IWorkingLocation extends IWorkingLocationRaw {
	personWorkingLocations?: IPaginationList<IPersonWorkingLocation>;
	companyWorkingLocations?: IPaginationList<ICompanyWorkingLocation>;
}
export interface IPersonWorkingLocationRaw extends IEntity {
	id: number;
	date: string;
	daySlotType: DaySlotType;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personId: number;
	workingLocationId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonWorkingLocation extends IPersonWorkingLocationRaw {
	person?: IPerson;
	workingLocation?: IWorkingLocation;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	personToWorkplaceBookings?: IPaginationList<IPersonToWorkplaceBooking>;
	personToRoomBookings?: IPaginationList<IPersonToRoomBooking>;
	personToDimensionBookings?: IPaginationList<IPersonToDimensionBooking>;
}
export interface IPersonToWorkplaceBookingRaw extends IEntity {
	id: number;
	startDatetime: string;
	endDatetime: string;
	workspaceHasBeenConfirmedAt?: string;
	emailConfirmationWarningNotificationSentAt?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personId: number;
	workplaceId: number;
	personWorkingLocationId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonToWorkplaceBooking extends IPersonToWorkplaceBookingRaw {
	person?: IPerson;
	workplace?: IWorkplace;
	personWorkingLocation?: IPersonWorkingLocation;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IWorkplaceAffectationRaw extends IEntity {
	id: number;
	rate?: number;
	calculatedRate?: number;
	mondayRate?: number;
	tuesdayRate?: number;
	wednesdayRate?: number;
	thursdayRate?: number;
	fridayRate?: number;
	saturdayRate?: number;
	sundayRate?: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personId: number;
	workplaceId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IWorkplaceAffectation extends IWorkplaceAffectationRaw {
	person?: IPerson;
	workplace?: IWorkplace;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IWorkplaceUsageTypeRaw extends IEntity {
	id: number;
	name: string;
	color: string;
	description?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IWorkplaceUsageType extends IWorkplaceUsageTypeRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	workplaces?: IPaginationList<IWorkplace>;
}
export interface IWorkplaceRaw extends IEntity {
	id: number;
	position: IPoint3d;
	rotation: number;
	isFlex?: boolean;
	isTransit?: boolean;
	isShared?: boolean;
	textAnchor?: ITextAnchor;
	name?: string;
	workplaceAffectationsCalculatedRateSum?: number;
	workplaceAffectationsCount?: number;
	comment?: string;
	isBookable?: boolean;
	isReleasable?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	workplaceTypeId: number;
	roomId: number;
	organizationId?: number | null;
	costCenterId?: number | null;
	workplaceUsageTypeId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IWorkplace extends IWorkplaceRaw {
	workplaceType?: IWorkplaceType;
	room?: IRoom;
	organization?: IOrganization;
	costCenter?: ICostCenter;
	workplaceUsageType?: IWorkplaceUsageType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	items?: IPaginationList<IItem>;
	workplaceAffectations?: IPaginationList<IWorkplaceAffectation>;
	personToWorkplaceBookings?: IPaginationList<IPersonToWorkplaceBooking>;
}
export interface IWorkplaceTypeRaw extends IEntity {
	id: number;
	name: string;
	zIndex: number;
	color?: string;
	center?: IPoint3d;
	size?: ISize;
	textAnchor?: ITextAnchor;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IWorkplaceType extends IWorkplaceTypeRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	workplaceTypeItemTypes?: IPaginationList<IWorkplaceTypeItemType>;
	workplaces?: IPaginationList<IWorkplace>;
}
export interface IWorkplaceTypeItemTypeRaw extends IEntity {
	id: number;
	position: IPoint3d;
	physicalInventory?: boolean;
	rotation: number;
	zIndex: number;
	seatsCount?: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	workplaceTypeId: number;
	itemTypeId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IWorkplaceTypeItemType extends IWorkplaceTypeItemTypeRaw {
	workplaceType?: IWorkplaceType;
	itemType?: IItemType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IItemTypeRaw extends IEntity {
	id: number;
	name: string;
	picture?: IJupImage;
	displayItemReferenceInMap?: boolean;
	code?: string;
	icon?: IJupIcon;
	color?: string;
	height?: number;
	zIndex: number;
	description?: string;
	price?: number;
	seatsCount?: number;
	carbonFootprint?: number;
	iconShape?: IconShapeType;
	iconBackgroundColor?: string;
	iconBorderColor?: string;
	iconBadge?: IItemTypeIconBadge;
	isAffectable?: boolean;
	excludeFromPathfinding?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	itemTypeFamilyId: number;
	manufacturerId?: number | null;
	object3dModelId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IItemType extends IItemTypeRaw {
	itemTypeFamily?: IItemTypeFamily;
	manufacturer?: IManufacturer;
	object3dModel?: IObject3dModel;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	itemTypePoints?: IPaginationList<IItemTypePoint>;
	itemTypeVisualEdges?: IPaginationList<IItemTypeVisualEdge>;
	workplaceTypeItemTypes?: IPaginationList<IWorkplaceTypeItemType>;
	items?: IPaginationList<IItem>;
	personCompanyToItemTypes?: IPaginationList<IPersonCompanyToItemType>;
}
export interface IItemRaw extends IEntity {
	id: number;
	code?: string;
	comment?: string;
	reference?: string;
	purchaseDate?: string;
	position: IPoint3d;
	rotation: number;
	textAnchor?: ITextAnchor;
	price?: number;
	itemAffectationsCount?: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	itemTypeId: number;
	roomId: number;
	workplaceId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IItem extends IItemRaw {
	itemType?: IItemType;
	room?: IRoom;
	workplace?: IWorkplace;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	itemToPeople?: IPaginationList<IItemToPerson>;
	personCompanyToItems?: IPaginationList<IPersonCompanyToItem>;
	itemFacts?: IPaginationList<IItemFact>;
}
export interface IPersonCompanyToItemRaw extends IEntity {
	id: number;
	datetime?: string;
	comment?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personCompanyId: number;
	itemId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonCompanyToItem extends IPersonCompanyToItemRaw {
	personCompany?: IPersonCompany;
	item?: IItem;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IPersonCompanyRaw extends IEntity {
	id: number;
	name: string;
	comment?: string;
	contact?: string;
	documents?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonCompany extends IPersonCompanyRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	people?: IPaginationList<IPerson>;
	personCompanyToItemTypes?: IPaginationList<IPersonCompanyToItemType>;
	personCompanyToRoomTypes?: IPaginationList<IPersonCompanyToRoomType>;
	personCompanyToItems?: IPaginationList<IPersonCompanyToItem>;
}
export interface IPersonCompanyToRoomTypeRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personCompanyId: number;
	roomTypeId: number;
	personCompanyMissionId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonCompanyToRoomType extends IPersonCompanyToRoomTypeRaw {
	personCompany?: IPersonCompany;
	roomType?: IRoomType;
	personCompanyMission?: IPersonCompanyMission;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IRoomTypeBuildingRaw extends IEntity {
	id: number;
	roomsArea: number;
	roomsCount: number;
	workplacesCount: number;
	workplacesRatio: number;
	peopleCount: number;
	seatsCount: number;
	peopleRatio: number;
	occupancyRate: number;
	expansionRatio: number;
	freeWorkplacesCount: number;
	flexWorkplacesCount: number;
	sharedWorkplacesCount: number;
	sharedWorkplacesRatio: number;
	transitWorkplacesCount: number;
	flexRatio: number;
	seatsPeopleRatio: number;
	totalPeopleCount: number;
	carbonFootprint: number;
	totalCapacityCount: number;
	totalCapacityWorkplaceCountRatio: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	roomTypeId: number;
	buildingId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomTypeBuilding extends IRoomTypeBuildingRaw {
	roomType?: IRoomType;
	building?: IBuilding;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IRoomTypeFloorRaw extends IEntity {
	id: number;
	roomsArea: number;
	roomsCount: number;
	workplacesCount: number;
	workplacesRatio: number;
	peopleCount: number;
	seatsCount: number;
	peopleRatio: number;
	occupancyRate: number;
	expansionRatio: number;
	freeWorkplacesCount: number;
	flexWorkplacesCount: number;
	sharedWorkplacesCount: number;
	sharedWorkplacesRatio: number;
	transitWorkplacesCount: number;
	flexRatio: number;
	seatsPeopleRatio: number;
	totalPeopleCount: number;
	carbonFootprint: number;
	totalCapacityCount: number;
	totalCapacityWorkplaceCountRatio: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	roomTypeId: number;
	floorId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomTypeFloor extends IRoomTypeFloorRaw {
	roomType?: IRoomType;
	floor?: IFloor;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IRoomTypeGroupBuildingRaw extends IEntity {
	id: number;
	roomsArea: number;
	roomsCount: number;
	workplacesCount: number;
	workplacesRatio: number;
	peopleCount: number;
	seatsCount: number;
	peopleRatio: number;
	occupancyRate: number;
	expansionRatio: number;
	freeWorkplacesCount: number;
	flexWorkplacesCount: number;
	sharedWorkplacesCount: number;
	sharedWorkplacesRatio: number;
	transitWorkplacesCount: number;
	flexRatio: number;
	seatsPeopleRatio: number;
	totalPeopleCount: number;
	carbonFootprint: number;
	totalCapacityCount: number;
	totalCapacityWorkplaceCountRatio: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	roomTypeGroupId: number;
	buildingId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomTypeGroupBuilding extends IRoomTypeGroupBuildingRaw {
	roomTypeGroup?: IRoomTypeGroup;
	building?: IBuilding;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IRoomTypeGroupFloorRaw extends IEntity {
	id: number;
	roomsArea: number;
	roomsCount: number;
	workplacesCount: number;
	workplacesRatio: number;
	peopleCount: number;
	seatsCount: number;
	peopleRatio: number;
	occupancyRate: number;
	expansionRatio: number;
	freeWorkplacesCount: number;
	flexWorkplacesCount: number;
	sharedWorkplacesCount: number;
	sharedWorkplacesRatio: number;
	transitWorkplacesCount: number;
	flexRatio: number;
	seatsPeopleRatio: number;
	totalPeopleCount: number;
	carbonFootprint: number;
	totalCapacityCount: number;
	totalCapacityWorkplaceCountRatio: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	roomTypeGroupId: number;
	floorId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomTypeGroupFloor extends IRoomTypeGroupFloorRaw {
	roomTypeGroup?: IRoomTypeGroup;
	floor?: IFloor;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IRoomTypeGroupRaw extends IEntity {
	id: number;
	name: string;
	code: string;
	color?: string;
	exclude?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IRoomTypeGroup extends IRoomTypeGroupRaw {
	roomTypeGroupToRoomTypes?: IPaginationList<IRoomTypeGroupToRoomType>;
	roomTypeGroupFloors?: IPaginationList<IRoomTypeGroupFloor>;
	roomTypeGroupBuildings?: IPaginationList<IRoomTypeGroupBuilding>;
}
export interface IRoomTypeGroupToRoomTypeRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	roomTypeGroupId: number;
	roomTypeId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomTypeGroupToRoomType extends IRoomTypeGroupToRoomTypeRaw {
	roomTypeGroup?: IRoomTypeGroup;
	roomType?: IRoomType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IRoomTypeRaw extends IEntity {
	id: number;
	name: string;
	color?: string;
	icon?: IJupIcon;
	color3d?: string;
	code?: string;
	displayWallsOn3d?: boolean;
	cadence?: number;
	isBookable?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	distributionCostTypeId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomType extends IRoomTypeRaw {
	distributionCostType?: IDistributionCostType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	roomTypeGroupToRoomTypes?: IPaginationList<IRoomTypeGroupToRoomType>;
	rooms?: IPaginationList<IRoom>;
	roomTypeFloors?: IPaginationList<IRoomTypeFloor>;
	roomTypeBuildings?: IPaginationList<IRoomTypeBuilding>;
	personCompanyToRoomTypes?: IPaginationList<IPersonCompanyToRoomType>;
	partnerExportMappingToRoomTypes?: IPaginationList<IPartnerExportMappingToRoomType>;
}
export interface IDistributionCostTypeRaw extends IEntity {
	id: number;
	name: string;
	code: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IDistributionCostType extends IDistributionCostTypeRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	roomTypes?: IPaginationList<IRoomType>;
	rooms?: IPaginationList<IRoom>;
}
export interface IOccupancyStatusRaw extends IEntity {
	id: number;
	name: string;
	code: string;
	color: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IOccupancyStatus extends IOccupancyStatusRaw {
	rooms?: IPaginationList<IRoom>;
}
export interface IRoomAffectationRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personId: number;
	roomId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomAffectation extends IRoomAffectationRaw {
	person?: IPerson;
	room?: IRoom;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IRoomConnectorTypeRaw extends IEntity {
	id: number;
	name: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IRoomConnectorType extends IRoomConnectorTypeRaw {
	roomConnectors?: IPaginationList<IRoomConnector>;
}
export interface IRoomConnectorRaw extends IEntity {
	id: number;
	name: string;
	waitTime?: number;
	timePerFloor?: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	roomConnectorTypeId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomConnector extends IRoomConnectorRaw {
	roomConnectorType?: IRoomConnectorType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	rooms?: IPaginationList<IRoom>;
}
export interface IRoomPointSegmentTypeRaw extends IEntity {
	id: number;
	name: string;
	code: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IRoomPointSegmentType extends IRoomPointSegmentTypeRaw {
	roomPointSegments?: IPaginationList<IRoomPointSegment>;
}
export interface IRoomPointSegmentRaw extends IEntity {
	id: number;
	reversePoints?: boolean;
	displayBothSides?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	roomPointSegmentTypeId: number;
	roomPointStartId: number;
	roomPointEndId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomPointSegment extends IRoomPointSegmentRaw {
	roomPointSegmentType?: IRoomPointSegmentType;
	roomPointStart?: IRoomPoint;
	roomPointEnd?: IRoomPoint;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IRoomPointRaw extends IEntity {
	id: number;
	x: number;
	y: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	floorId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomPoint extends IRoomPointRaw {
	floor?: IFloor;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	roomPointRooms?: IPaginationList<IRoomPointRoom>;
	roomPointSegmentStarts?: IPaginationList<IRoomPointSegment>;
	roomPointSegmentEnds?: IPaginationList<IRoomPointSegment>;
}
export interface IRoomPointRoomRaw extends IEntity {
	id: number;
	sortIndex: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	roomId: number;
	roomPointId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoomPointRoom extends IRoomPointRoomRaw {
	room?: IRoom;
	roomPoint?: IRoomPoint;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IRoomRaw extends IEntity {
	id: number;
	name?: string;
	prettyName?: string;
	area?: number;
	perimeter?: number;
	textAnchor?: ITextAnchor;
	capacity?: number;
	workplacesCount?: number;
	workplacesRatio?: number;
	peopleCount?: number;
	seatsCount?: number;
	peopleRatio?: number;
	occupancyRate?: number;
	expansionRatio?: number;
	freeWorkplacesCount?: number;
	flexWorkplacesCount?: number;
	sharedWorkplacesCount?: number;
	sharedWorkplacesRatio?: number;
	transitWorkplacesCount?: number;
	flexRatio?: number;
	seatsPeopleRatio?: number;
	totalPeopleCount?: number;
	carbonFootprint?: number;
	totalCapacityCount?: number;
	totalCapacityWorkplaceCountRatio?: number;
	info?: string;
	bookingEmail?: string;
	externalId2?: string;
	picture?: IJupImage;
	keyCylinderCode?: string;
	livePeopleCount?: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	floorId: number;
	occupancyStatusId?: number | null;
	roomTypeId?: number | null;
	organizationId?: number | null;
	costCenterId?: number | null;
	distributionCostTypeId?: number | null;
	roomConnectorId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IRoom extends IRoomRaw {
	floor?: IFloor;
	occupancyStatus?: IOccupancyStatus;
	roomType?: IRoomType;
	organization?: IOrganization;
	costCenter?: ICostCenter;
	distributionCostType?: IDistributionCostType;
	roomConnector?: IRoomConnector;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	roomPointRooms?: IPaginationList<IRoomPointRoom>;
	dimensionRooms?: IPaginationList<IDimensionRoom>;
	roomAffectations?: IPaginationList<IRoomAffectation>;
	workplaces?: IPaginationList<IWorkplace>;
	items?: IPaginationList<IItem>;
	personToRoomBookings?: IPaginationList<IPersonToRoomBooking>;
}
export interface IDimensionRoomRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	dimensionId: number;
	roomId: number;
	dimensionTypeId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IDimensionRoom extends IDimensionRoomRaw {
	dimension?: IDimension;
	room?: IRoom;
	dimensionType?: IDimensionType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IDimensionTypeToBuildingRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	dimensionTypeId: number;
	buildingId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IDimensionTypeToBuilding extends IDimensionTypeToBuildingRaw {
	dimensionType?: IDimensionType;
	building?: IBuilding;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IDimensionTypeRaw extends IEntity {
	id: number;
	name: string;
	code?: string;
	order?: number;
	description?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IDimensionType extends IDimensionTypeRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	dimensions?: IPaginationList<IDimension>;
	dimensionRooms?: IPaginationList<IDimensionRoom>;
	dimensionFloors?: IPaginationList<IDimensionFloor>;
	dimensionBuildings?: IPaginationList<IDimensionBuilding>;
	dimensionTypeToBuildings?: IPaginationList<IDimensionTypeToBuilding>;
}
export interface IDimensionBuildingRaw extends IEntity {
	id: number;
	dimensionPeopleCount: number;
	bookableWorkplacesCount?: number;
	roomsArea: number;
	roomsCount: number;
	workplacesCount: number;
	workplacesRatio: number;
	peopleCount: number;
	seatsCount: number;
	peopleRatio: number;
	occupancyRate: number;
	expansionRatio: number;
	freeWorkplacesCount: number;
	flexWorkplacesCount: number;
	sharedWorkplacesCount: number;
	sharedWorkplacesRatio: number;
	transitWorkplacesCount: number;
	flexRatio: number;
	seatsPeopleRatio: number;
	totalPeopleCount: number;
	carbonFootprint: number;
	totalCapacityCount: number;
	totalCapacityWorkplaceCountRatio: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	dimensionId?: number | null;
	dimensionTypeId: number;
	buildingId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IDimensionBuilding extends IDimensionBuildingRaw {
	dimension?: IDimension;
	dimensionType?: IDimensionType;
	building?: IBuilding;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IDimensionRaw extends IEntity {
	id: number;
	name: string;
	color?: string;
	value?: number;
	peopleCount?: number;
	totalPeopleCount?: number;
	manualPeopleCount?: number;
	carbonFootprintPerMeter?: number;
	crowdedForBookingRate?: number;
	workplacesBookableOnlyViaDimension?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	dimensionTypeId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IDimension extends IDimensionRaw {
	dimensionType?: IDimensionType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	dimensionRooms?: IPaginationList<IDimensionRoom>;
	dimensionFloors?: IPaginationList<IDimensionFloor>;
	dimensionBuildings?: IPaginationList<IDimensionBuilding>;
	dimensionToPeople?: IPaginationList<IDimensionToPerson>;
	personToDimensionBookings?: IPaginationList<IPersonToDimensionBooking>;
}
export interface IDimensionToPersonRaw extends IEntity {
	id: number;
	priority?: number;
	addToPeopleCount?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	dimensionId: number;
	personId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IDimensionToPerson extends IDimensionToPersonRaw {
	dimension?: IDimension;
	person?: IPerson;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IPersonGenderRaw extends IEntity {
	id: number;
	name: string;
	code: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IPersonGender extends IPersonGenderRaw {
	people?: IPaginationList<IPerson>;
}
export interface IPersonSecurityProfileRaw extends IEntity {
	id: number;
	name: string;
	color?: string;
	icon?: IJupIcon;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonSecurityProfile extends IPersonSecurityProfileRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	people?: IPaginationList<IPerson>;
}
export interface IPersonStateRaw extends IEntity {
	id: number;
	name: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonState extends IPersonStateRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	people?: IPaginationList<IPerson>;
}
export interface IPersonToBuildingRaw extends IEntity {
	id: number;
	addToPeopleCount?: boolean;
	allowWorkplaceBookingInTheBuilding?: boolean;
	allowParkingBookingInTheBuilding?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personId: number;
	buildingId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonToBuilding extends IPersonToBuildingRaw {
	person?: IPerson;
	building?: IBuilding;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IPersonToPersonTypeRaw extends IEntity {
	id: number;
	labelForward: string;
	labelBackward: string;
	code?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonToPersonType extends IPersonToPersonTypeRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	personToPeople?: IPaginationList<IPersonToPerson>;
}
export interface IPersonToPersonRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personToPersonTypeId?: number | null;
	personSourceId: number;
	personTargetId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonToPerson extends IPersonToPersonRaw {
	personToPersonType?: IPersonToPersonType;
	personSource?: IPerson;
	personTarget?: IPerson;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IBookingVehicleConfigurationToParkingRoomTypeConfigurationRaw extends IEntity {
	id: number;
	allowDaySlotAm: boolean;
	allowDaySlotPm: boolean;
	allowDaySlotAll: boolean;
	singleBookingPerDay: boolean;
	parkingRoomTypeCode: ParkingRoomTypeCode;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	bookingVehicleConfigurationId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IBookingVehicleConfigurationToParkingRoomTypeConfiguration extends IBookingVehicleConfigurationToParkingRoomTypeConfigurationRaw {
	bookingVehicleConfiguration?: IBookingVehicleConfiguration;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IVehicleTypeRaw extends IEntity {
	id: number;
	name: string;
	color: string;
	code: string;
	icon?: IJupIcon;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IVehicleType extends IVehicleTypeRaw {
	vehicles?: IPaginationList<IVehicle>;
	bookingVehicleConfigurations?: IPaginationList<IBookingVehicleConfiguration>;
}
export interface IBookingVehicleConfigurationRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	vehicleTypeId: number;
	vehiclePropulsionTypeId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IBookingVehicleConfiguration extends IBookingVehicleConfigurationRaw {
	vehicleType?: IVehicleType;
	vehiclePropulsionType?: IVehiclePropulsionType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	bookingVehicleConfigurationToParkingRoomTypeConfigurations?: IPaginationList<IBookingVehicleConfigurationToParkingRoomTypeConfiguration>;
}
export interface IVehiclePropulsionTypeRaw extends IEntity {
	id: number;
	name: string;
	color: string;
	code: string;
	icon?: IJupIcon;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IVehiclePropulsionType extends IVehiclePropulsionTypeRaw {
	vehicles?: IPaginationList<IVehicle>;
	bookingVehicleConfigurations?: IPaginationList<IBookingVehicleConfiguration>;
}
export interface IVehicleRaw extends IEntity {
	id: number;
	belongsToTheCompany?: boolean;
	vehicleRegistration?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	vehicleTypeId: number;
	vehiclePropulsionTypeId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IVehicle extends IVehicleRaw {
	vehicleType?: IVehicleType;
	vehiclePropulsionType?: IVehiclePropulsionType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	personToVehicles?: IPaginationList<IPersonToVehicle>;
}
export interface IPersonToVehicleRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	personId: number;
	vehicleId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPersonToVehicle extends IPersonToVehicleRaw {
	person?: IPerson;
	vehicle?: IVehicle;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IPersonTypeRaw extends IEntity {
	id: number;
	name: string;
	code: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IPersonType extends IPersonTypeRaw {
	people?: IPaginationList<IPerson>;
}
export interface IPersonRaw extends IEntity {
	id: number;
	firstname: string;
	lastname: string;
	fullname?: string;
	email?: string;
	picture?: IJupImage;
	title?: string;
	monitorReference?: string;
	computerReference?: string;
	telephone?: string;
	cellphone?: string;
	code?: string;
	badgeNumber?: string;
	badgeRestaurant?: string;
	boxNumber?: string;
	registrationNumber?: string;
	startDate?: string;
	endDate?: string;
	info?: string;
	notAffectable?: boolean;
	notAffectableEndDate?: string;
	workflow?: string;
	mainLocation?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	organizationId?: number | null;
	personStateId?: number | null;
	personSecurityProfileId?: number | null;
	costCenterId?: number | null;
	personCompanyId?: number | null;
	personGenderId?: number | null;
	personTypeId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPerson extends IPersonRaw {
	organization?: IOrganization;
	personState?: IPersonState;
	personSecurityProfile?: IPersonSecurityProfile;
	costCenter?: ICostCenter;
	personCompany?: IPersonCompany;
	personGender?: IPersonGender;
	personType?: IPersonType;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	userCompanies?: IPaginationList<IUserCompany>;
	personToPersonSources?: IPaginationList<IPersonToPerson>;
	personToPersonTargets?: IPaginationList<IPersonToPerson>;
	personToVehicles?: IPaginationList<IPersonToVehicle>;
	roomAffectations?: IPaginationList<IRoomAffectation>;
	workplaceAffectations?: IPaginationList<IWorkplaceAffectation>;
	itemToPeople?: IPaginationList<IItemToPerson>;
	personToBuildings?: IPaginationList<IPersonToBuilding>;
	dimensionToPeople?: IPaginationList<IDimensionToPerson>;
	personWorkingLocations?: IPaginationList<IPersonWorkingLocation>;
	personToWorkplaceBookings?: IPaginationList<IPersonToWorkplaceBooking>;
	personToRoomBookings?: IPaginationList<IPersonToRoomBooking>;
	personToDimensionBookings?: IPaginationList<IPersonToDimensionBooking>;
}
export interface ICostCenterRaw extends IEntity {
	id: number;
	name: string;
	color?: string;
	info?: string;
	distributeByFloor?: boolean;
	distributeByBuilding?: boolean;
	code?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface ICostCenter extends ICostCenterRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	costCenterBuildings?: IPaginationList<ICostCenterBuilding>;
	costCenterFloors?: IPaginationList<ICostCenterFloor>;
	rooms?: IPaginationList<IRoom>;
	people?: IPaginationList<IPerson>;
	workplaces?: IPaginationList<IWorkplace>;
}
export interface ICostCenterFloorRaw extends IEntity {
	id: number;
	roomsArea: number;
	roomsCount: number;
	workplacesCount: number;
	workplacesRatio: number;
	peopleCount: number;
	seatsCount: number;
	peopleRatio: number;
	occupancyRate: number;
	expansionRatio: number;
	freeWorkplacesCount: number;
	flexWorkplacesCount: number;
	sharedWorkplacesCount: number;
	sharedWorkplacesRatio: number;
	transitWorkplacesCount: number;
	flexRatio: number;
	seatsPeopleRatio: number;
	totalPeopleCount: number;
	carbonFootprint: number;
	totalCapacityCount: number;
	totalCapacityWorkplaceCountRatio: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	costCenterId: number;
	floorId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface ICostCenterFloor extends ICostCenterFloorRaw {
	costCenter?: ICostCenter;
	floor?: IFloor;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IMapScaleRaw extends IEntity {
	id: number;
	name?: string;
	p1: IPoint2d;
	p2: IPoint2d;
	length?: number;
	ratio?: number;
	strokeWidth?: number;
	roomTextSize?: number;
	workplaceTextSize?: number;
	segmentDistanceTextSize?: number;
	itemTypeIconSize?: number;
	roomIconSize?: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IMapScale extends IMapScaleRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	floors?: IPaginationList<IFloor>;
}
export interface IStructurePointRaw extends IEntity {
	id: number;
	x: number;
	y: number;
	sortIndex: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	structureId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IStructurePoint extends IStructurePointRaw {
	structure?: IStructure;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IStructureRaw extends IEntity {
	id: number;
	name: string;
	transform?: IJupTransform;
	anchorLatLng?: IJupAddress;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IStructure extends IStructureRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	structurePoints?: IPaginationList<IStructurePoint>;
	floors?: IPaginationList<IFloor>;
}
export interface IFloorRaw extends IEntity {
	id: number;
	name: string;
	level: number;
	height?: number;
	regulatoryCapacity?: number;
	roomsArea?: number;
	roomsCount?: number;
	workplacesCount?: number;
	workplacesRatio?: number;
	peopleCount?: number;
	seatsCount?: number;
	peopleRatio?: number;
	occupancyRate?: number;
	expansionRatio?: number;
	freeWorkplacesCount?: number;
	flexWorkplacesCount?: number;
	sharedWorkplacesCount?: number;
	sharedWorkplacesRatio?: number;
	transitWorkplacesCount?: number;
	flexRatio?: number;
	seatsPeopleRatio?: number;
	totalPeopleCount?: number;
	carbonFootprint?: number;
	totalCapacityCount?: number;
	totalCapacityWorkplaceCountRatio?: number;
	backgroundLayout?: IJupImage;
	backgroundLayoutOpacity?: number;
	pathfindingGraph?: IFloorPathfindingGraph;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	buildingId: number;
	mapScaleId?: number | null;
	structureId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IFloor extends IFloorRaw {
	building?: IBuilding;
	mapScale?: IMapScale;
	structure?: IStructure;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	roomTypeGroupFloors?: IPaginationList<IRoomTypeGroupFloor>;
	costCenterFloors?: IPaginationList<ICostCenterFloor>;
	rooms?: IPaginationList<IRoom>;
	roomPoints?: IPaginationList<IRoomPoint>;
	dimensionFloors?: IPaginationList<IDimensionFloor>;
	organizationFloors?: IPaginationList<IOrganizationFloor>;
	roomTypeFloors?: IPaginationList<IRoomTypeFloor>;
	contentRoleToFloors?: IPaginationList<IContentRoleToFloor>;
	partnerExportMappingConfigurationToFloors?: IPaginationList<IPartnerExportMappingConfigurationToFloor>;
}
export interface IContentRoleToFloorRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	contentRoleId: number;
	floorId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IContentRoleToFloor extends IContentRoleToFloorRaw {
	contentRole?: IContentRole;
	floor?: IFloor;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IJupUiTenantOperationRaw extends IEntity {
	id: number;
	name: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IJupUiTenantOperation extends IJupUiTenantOperationRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	contentRoleToJupUiTenantOperations?: IPaginationList<IContentRoleToJupUiTenantOperation>;
}
export interface IContentRoleToJupUiTenantOperationRaw extends IEntity {
	id: number;
	canSee?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	jupUiTenantOperationId: number;
	contentRoleId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IContentRoleToJupUiTenantOperation extends IContentRoleToJupUiTenantOperationRaw {
	jupUiTenantOperation?: IJupUiTenantOperation;
	contentRole?: IContentRole;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IContentRoleToUserCompanyRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyId: number;
	contentRoleId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IContentRoleToUserCompany extends IContentRoleToUserCompanyRaw {
	userCompany?: IUserCompany;
	contentRole?: IContentRole;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IAuthentificationConnectionRaw extends IEntity {
	id: number;
	name: string;
	publicIdpCertificate?: string;
	domaines?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IAuthentificationConnection extends IAuthentificationConnectionRaw {
	userRegistrationTenantRules?: IPaginationList<IUserRegistrationTenantRule>;
}
export interface IApiUserToJupRoleRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	apiUserId: number;
	jupRoleId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IApiUserToJupRole extends IApiUserToJupRoleRaw {
	apiUser?: IApiUser;
	jupRole?: IJupRole;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IJupRoleToJupUiViewRaw extends IEntity {
	id: number;
	canSee?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	jupUiViewId: number;
	jupRoleId: number;
}
export interface IJupRoleToJupUiView extends IJupRoleToJupUiViewRaw {
	jupUiView?: IJupUiView;
	jupRole?: IJupRole;
}
export interface IJupUiViewRaw extends IEntity {
	id: number;
	name: string;
	isDefaultView?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	jupObjectTypeId: number;
}
export interface IJupUiView extends IJupUiViewRaw {
	jupObjectType?: IJupObjectType;
	jupRoleToJupUiViews?: IPaginationList<IJupRoleToJupUiView>;
}
export interface IJupObjectTypeRaw extends IEntity {
	id: number;
	name: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IJupObjectType extends IJupObjectTypeRaw {
	jupUiViews?: IPaginationList<IJupUiView>;
	jupRoleToJupObjectTypes?: IPaginationList<IJupRoleToJupObjectType>;
}
export interface IJupRoleToJupObjectTypeRaw extends IEntity {
	id: number;
	arCreate?: boolean;
	arRead?: boolean;
	arUpdate?: boolean;
	arDelete?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	jupObjectTypeId: number;
	jupRoleId: number;
}
export interface IJupRoleToJupObjectType extends IJupRoleToJupObjectTypeRaw {
	jupObjectType?: IJupObjectType;
	jupRole?: IJupRole;
}
export interface IJupUiLayoutRaw extends IEntity {
	id: number;
	name: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IJupUiLayout extends IJupUiLayoutRaw {
	buildings?: IPaginationList<IBuilding>;
	jupRoleToJupUiLayouts?: IPaginationList<IJupRoleToJupUiLayout>;
}
export interface IJupRoleToJupUiLayoutRaw extends IEntity {
	id: number;
	canSee?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	jupUiLayoutId: number;
	jupRoleId: number;
}
export interface IJupRoleToJupUiLayout extends IJupRoleToJupUiLayoutRaw {
	jupUiLayout?: IJupUiLayout;
	jupRole?: IJupRole;
}
export interface IJupUiLayoutTabRaw extends IEntity {
	id: number;
	name: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IJupUiLayoutTab extends IJupUiLayoutTabRaw {
	jupRoleToJupUiLayoutTabs?: IPaginationList<IJupRoleToJupUiLayoutTab>;
}
export interface IJupRoleToJupUiLayoutTabRaw extends IEntity {
	id: number;
	canSee?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	jupUiLayoutTabId: number;
	jupRoleId: number;
}
export interface IJupRoleToJupUiLayoutTab extends IJupRoleToJupUiLayoutTabRaw {
	jupUiLayoutTab?: IJupUiLayoutTab;
	jupRole?: IJupRole;
}
export interface IJupUiOperationRaw extends IEntity {
	id: number;
	name: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IJupUiOperation extends IJupUiOperationRaw {
	jupRoleToJupUiOperations?: IPaginationList<IJupRoleToJupUiOperation>;
}
export interface IJupRoleToJupUiOperationRaw extends IEntity {
	id: number;
	canSee?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	jupUiOperationId: number;
	jupRoleId: number;
}
export interface IJupRoleToJupUiOperation extends IJupRoleToJupUiOperationRaw {
	jupUiOperation?: IJupUiOperation;
	jupRole?: IJupRole;
}
export interface IJupUiOptionRaw extends IEntity {
	id: number;
	name: string;
	scope?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IJupUiOption extends IJupUiOptionRaw {
	jupRoleToJupUiOptions?: IPaginationList<IJupRoleToJupUiOption>;
}
export interface IJupRoleToJupUiOptionRaw extends IEntity {
	id: number;
	canSee?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	jupUiOptionId: number;
	jupRoleId: number;
}
export interface IJupRoleToJupUiOption extends IJupRoleToJupUiOptionRaw {
	jupUiOption?: IJupUiOption;
	jupRole?: IJupRole;
}
export interface IJupUserCompanyToJupRoleRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyId: number;
	jupRoleId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IJupUserCompanyToJupRole extends IJupUserCompanyToJupRoleRaw {
	userCompany?: IUserCompany;
	jupRole?: IJupRole;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IJupRoleRaw extends IEntity {
	id: number;
	code: string;
	name?: string;
	isClaim?: boolean;
	excludeScenarios?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IJupRole extends IJupRoleRaw {
	jupUserCompanyToJupRoles?: IPaginationList<IJupUserCompanyToJupRole>;
	jupRoleToJupUiViews?: IPaginationList<IJupRoleToJupUiView>;
	jupRoleToJupObjectTypes?: IPaginationList<IJupRoleToJupObjectType>;
	jupRoleToJupUiOptions?: IPaginationList<IJupRoleToJupUiOption>;
	jupRoleToJupUiOperations?: IPaginationList<IJupRoleToJupUiOperation>;
	apiUserToJupRoles?: IPaginationList<IApiUserToJupRole>;
	userRegistrationTenantRuleToJupRoles?: IPaginationList<IUserRegistrationTenantRuleToJupRole>;
	jupRoleToJupUiLayouts?: IPaginationList<IJupRoleToJupUiLayout>;
	jupRoleToJupUiLayoutTabs?: IPaginationList<IJupRoleToJupUiLayoutTab>;
}
export interface IUserRegistrationTenantRuleToJupRoleRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userRegistrationTenantRuleId: number;
	jupRoleId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IUserRegistrationTenantRuleToJupRole extends IUserRegistrationTenantRuleToJupRoleRaw {
	userRegistrationTenantRule?: IUserRegistrationTenantRule;
	jupRole?: IJupRole;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IUserRegistrationTenantRuleRaw extends IEntity {
	id: number;
	name?: string;
	domains?: string;
	automaticUserToRoleMapping?: boolean;
	useOpenIdTokenRoleMapping?: boolean;
	useOpenIdTokenClaimsToAssociateToTenant?: boolean;
	jwtTokenTenantMappingPropertyName?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	authentificationConnectionId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IUserRegistrationTenantRule extends IUserRegistrationTenantRuleRaw {
	authentificationConnection?: IAuthentificationConnection;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	userRegistrationTenantRuleToJupRoles?: IPaginationList<IUserRegistrationTenantRuleToJupRole>;
	userRegistrationTenantRuleToContentRoles?: IPaginationList<IUserRegistrationTenantRuleToContentRole>;
}
export interface IUserRegistrationTenantRuleToContentRoleRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userRegistrationTenantRuleId: number;
	contentRoleId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IUserRegistrationTenantRuleToContentRole extends IUserRegistrationTenantRuleToContentRoleRaw {
	userRegistrationTenantRule?: IUserRegistrationTenantRule;
	contentRole?: IContentRole;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IContentRoleRaw extends IEntity {
	id: number;
	name?: string;
	code?: string;
	isClaim?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IContentRole extends IContentRoleRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	contentRoleToBuildings?: IPaginationList<IContentRoleToBuilding>;
	contentRoleToUserCompanies?: IPaginationList<IContentRoleToUserCompany>;
	contentRoleToFloors?: IPaginationList<IContentRoleToFloor>;
	apiUserToContentRoles?: IPaginationList<IApiUserToContentRole>;
	contentRoleToJupUiTenantOperations?: IPaginationList<IContentRoleToJupUiTenantOperation>;
	userRegistrationTenantRuleToContentRoles?: IPaginationList<IUserRegistrationTenantRuleToContentRole>;
}
export interface IApiUserToContentRoleRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	apiUserId: number;
	contentRoleId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IApiUserToContentRole extends IApiUserToContentRoleRaw {
	apiUser?: IApiUser;
	contentRole?: IContentRole;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IApiUserRaw extends IEntity {
	id: number;
	clientSecret: string;
	name?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IApiUser extends IApiUserRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	apiUserToJupRoles?: IPaginationList<IApiUserToJupRole>;
	apiUserToContentRoles?: IPaginationList<IApiUserToContentRole>;
}
export interface ICampusRaw extends IEntity {
	id: number;
	name: string;
	color: string;
	address?: IJupAddress;
	roomsArea?: number;
	roomsCount?: number;
	workplacesCount?: number;
	workplacesRatio?: number;
	peopleCount?: number;
	seatsCount?: number;
	peopleRatio?: number;
	occupancyRate?: number;
	expansionRatio?: number;
	freeWorkplacesCount?: number;
	flexWorkplacesCount?: number;
	sharedWorkplacesCount?: number;
	sharedWorkplacesRatio?: number;
	transitWorkplacesCount?: number;
	flexRatio?: number;
	seatsPeopleRatio?: number;
	totalPeopleCount?: number;
	carbonFootprint?: number;
	totalCapacityCount?: number;
	totalCapacityWorkplaceCountRatio?: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface ICampus extends ICampusRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	buildings?: IPaginationList<IBuilding>;
}
export interface IFactTypeRaw extends IEntity {
	id: number;
	name: string;
	code: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IFactType extends IFactTypeRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	facts?: IPaginationList<IFact>;
}
export interface IFactRaw extends IEntity {
	id: number;
	value: number;
	date: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	factTypeId: number;
	buildingId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IFact extends IFactRaw {
	factType?: IFactType;
	building?: IBuilding;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IFeatureFamilyRaw extends IEntity {
	id: number;
	name?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IFeatureFamily extends IFeatureFamilyRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	featureGroups?: IPaginationList<IFeatureGroup>;
}
export interface IFeatureGroupRaw extends IEntity {
	id: number;
	name?: string;
	sortOrder?: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	featureFamilyId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IFeatureGroup extends IFeatureGroupRaw {
	featureFamily?: IFeatureFamily;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
	features?: IPaginationList<IFeature>;
}
export interface IFeatureRaw extends IEntity {
	id: number;
	name?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	featureGroupId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IFeature extends IFeatureRaw {
	featureGroup?: IFeatureGroup;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface ILegendRaw extends IEntity {
	id: number;
	name: string;
	configuration?: IJupLegendConfiguration;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface ILegend extends ILegendRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IOpenerPostMessageHostRaw extends IEntity {
	id: number;
	host: string;
	description?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IOpenerPostMessageHost extends IOpenerPostMessageHostRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IPartnerApiCredentialRaw extends IEntity {
	id: number;
	label: string;
	code: string;
	host: string;
	clientId: string;
	clientSecret: string;
	enable?: boolean;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
	companyId?: number | null;
}
export interface IPartnerApiCredential extends IPartnerApiCredentialRaw {
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	company?: ICompany;
}
export interface IUserRefreshTokenRaw extends IEntity {
	id: number;
	refreshToken?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userId: number;
}
export interface IUserRefreshToken extends IUserRefreshTokenRaw {
	user?: IUser;
}
export interface IUserRaw extends IEntity {
	id: number;
	email: string;
	firstname?: string;
	lastname?: string;
	picture?: IJupImage;
	sub: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
}
export interface IUser extends IUserRaw {
	userRefreshTokens?: IPaginationList<IUserRefreshToken>;
	userCompanies?: IPaginationList<IUserCompany>;
}
export interface IUserCompanyRaw extends IEntity {
	id: number;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	userId: number;
	companyId: number;
	personId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
}
export interface IUserCompany extends IUserCompanyRaw {
	user?: IUser;
	company?: ICompany;
	person?: IPerson;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	campusCreatedBies?: IPaginationList<ICampus>;
	campusUpdatedBies?: IPaginationList<ICampus>;
	roomConnectorCreatedBies?: IPaginationList<IRoomConnector>;
	roomConnectorUpdatedBies?: IPaginationList<IRoomConnector>;
	userCompanyCreatedBies?: IPaginationList<IUserCompany>;
	userCompanyUpdatedBies?: IPaginationList<IUserCompany>;
	personCompanyCreatedBies?: IPaginationList<IPersonCompany>;
	personCompanyUpdatedBies?: IPaginationList<IPersonCompany>;
	buildingTypeCreatedBies?: IPaginationList<IBuildingType>;
	buildingTypeUpdatedBies?: IPaginationList<IBuildingType>;
	organizationCreatedBies?: IPaginationList<IOrganization>;
	organizationUpdatedBies?: IPaginationList<IOrganization>;
	itemTypeFamilyCreatedBies?: IPaginationList<IItemTypeFamily>;
	itemTypeFamilyUpdatedBies?: IPaginationList<IItemTypeFamily>;
	manufacturerCreatedBies?: IPaginationList<IManufacturer>;
	manufacturerUpdatedBies?: IPaginationList<IManufacturer>;
	itemTypeCreatedBies?: IPaginationList<IItemType>;
	itemTypeUpdatedBies?: IPaginationList<IItemType>;
	buildingOwners?: IPaginationList<IBuilding>;
	buildingCreatedBies?: IPaginationList<IBuilding>;
	buildingUpdatedBies?: IPaginationList<IBuilding>;
	mapScaleCreatedBies?: IPaginationList<IMapScale>;
	mapScaleUpdatedBies?: IPaginationList<IMapScale>;
	structureCreatedBies?: IPaginationList<IStructure>;
	structureUpdatedBies?: IPaginationList<IStructure>;
	structurePointCreatedBies?: IPaginationList<IStructurePoint>;
	structurePointUpdatedBies?: IPaginationList<IStructurePoint>;
	floorCreatedBies?: IPaginationList<IFloor>;
	floorUpdatedBies?: IPaginationList<IFloor>;
	distributionCostTypeCreatedBies?: IPaginationList<IDistributionCostType>;
	distributionCostTypeUpdatedBies?: IPaginationList<IDistributionCostType>;
	roomTypeCreatedBies?: IPaginationList<IRoomType>;
	roomTypeUpdatedBies?: IPaginationList<IRoomType>;
	roomTypeGroupToRoomTypeCreatedBies?: IPaginationList<IRoomTypeGroupToRoomType>;
	roomTypeGroupToRoomTypeUpdatedBies?: IPaginationList<IRoomTypeGroupToRoomType>;
	roomTypeGroupFloorCreatedBies?: IPaginationList<IRoomTypeGroupFloor>;
	roomTypeGroupFloorUpdatedBies?: IPaginationList<IRoomTypeGroupFloor>;
	roomTypeGroupBuildingCreatedBies?: IPaginationList<IRoomTypeGroupBuilding>;
	roomTypeGroupBuildingUpdatedBies?: IPaginationList<IRoomTypeGroupBuilding>;
	costCenterCreatedBies?: IPaginationList<ICostCenter>;
	costCenterUpdatedBies?: IPaginationList<ICostCenter>;
	costCenterBuildingCreatedBies?: IPaginationList<ICostCenterBuilding>;
	costCenterBuildingUpdatedBies?: IPaginationList<ICostCenterBuilding>;
	costCenterFloorCreatedBies?: IPaginationList<ICostCenterFloor>;
	costCenterFloorUpdatedBies?: IPaginationList<ICostCenterFloor>;
	roomCreatedBies?: IPaginationList<IRoom>;
	roomUpdatedBies?: IPaginationList<IRoom>;
	roomPointCreatedBies?: IPaginationList<IRoomPoint>;
	roomPointUpdatedBies?: IPaginationList<IRoomPoint>;
	roomPointRoomCreatedBies?: IPaginationList<IRoomPointRoom>;
	roomPointRoomUpdatedBies?: IPaginationList<IRoomPointRoom>;
	roomPointSegmentCreatedBies?: IPaginationList<IRoomPointSegment>;
	roomPointSegmentUpdatedBies?: IPaginationList<IRoomPointSegment>;
	itemTypePointCreatedBies?: IPaginationList<IItemTypePoint>;
	itemTypePointUpdatedBies?: IPaginationList<IItemTypePoint>;
	itemTypeVisualEdgeCreatedBies?: IPaginationList<IItemTypeVisualEdge>;
	itemTypeVisualEdgeUpdatedBies?: IPaginationList<IItemTypeVisualEdge>;
	dimensionTypeCreatedBies?: IPaginationList<IDimensionType>;
	dimensionTypeUpdatedBies?: IPaginationList<IDimensionType>;
	dimensionCreatedBies?: IPaginationList<IDimension>;
	dimensionUpdatedBies?: IPaginationList<IDimension>;
	dimensionRoomCreatedBies?: IPaginationList<IDimensionRoom>;
	dimensionRoomUpdatedBies?: IPaginationList<IDimensionRoom>;
	dimensionFloorCreatedBies?: IPaginationList<IDimensionFloor>;
	dimensionFloorUpdatedBies?: IPaginationList<IDimensionFloor>;
	dimensionBuildingCreatedBies?: IPaginationList<IDimensionBuilding>;
	dimensionBuildingUpdatedBies?: IPaginationList<IDimensionBuilding>;
	factTypeCreatedBies?: IPaginationList<IFactType>;
	factTypeUpdatedBies?: IPaginationList<IFactType>;
	factCreatedBies?: IPaginationList<IFact>;
	factUpdatedBies?: IPaginationList<IFact>;
	personStateCreatedBies?: IPaginationList<IPersonState>;
	personStateUpdatedBies?: IPaginationList<IPersonState>;
	personSecurityProfileCreatedBies?: IPaginationList<IPersonSecurityProfile>;
	personSecurityProfileUpdatedBies?: IPaginationList<IPersonSecurityProfile>;
	personCreatedBies?: IPaginationList<IPerson>;
	personUpdatedBies?: IPaginationList<IPerson>;
	personToPersonTypeCreatedBies?: IPaginationList<IPersonToPersonType>;
	personToPersonTypeUpdatedBies?: IPaginationList<IPersonToPersonType>;
	personToPersonCreatedBies?: IPaginationList<IPersonToPerson>;
	personToPersonUpdatedBies?: IPaginationList<IPersonToPerson>;
	vehicleCreatedBies?: IPaginationList<IVehicle>;
	vehicleUpdatedBies?: IPaginationList<IVehicle>;
	personToVehicleCreatedBies?: IPaginationList<IPersonToVehicle>;
	personToVehicleUpdatedBies?: IPaginationList<IPersonToVehicle>;
	roomAffectationCreatedBies?: IPaginationList<IRoomAffectation>;
	roomAffectationUpdatedBies?: IPaginationList<IRoomAffectation>;
	workplaceTypeCreatedBies?: IPaginationList<IWorkplaceType>;
	workplaceTypeUpdatedBies?: IPaginationList<IWorkplaceType>;
	workplaceUsageTypeCreatedBies?: IPaginationList<IWorkplaceUsageType>;
	workplaceUsageTypeUpdatedBies?: IPaginationList<IWorkplaceUsageType>;
	workplaceTypeItemTypeCreatedBies?: IPaginationList<IWorkplaceTypeItemType>;
	workplaceTypeItemTypeUpdatedBies?: IPaginationList<IWorkplaceTypeItemType>;
	workplaceCreatedBies?: IPaginationList<IWorkplace>;
	workplaceUpdatedBies?: IPaginationList<IWorkplace>;
	itemCreatedBies?: IPaginationList<IItem>;
	itemUpdatedBies?: IPaginationList<IItem>;
	workplaceAffectationCreatedBies?: IPaginationList<IWorkplaceAffectation>;
	workplaceAffectationUpdatedBies?: IPaginationList<IWorkplaceAffectation>;
	organizationFloorCreatedBies?: IPaginationList<IOrganizationFloor>;
	organizationFloorUpdatedBies?: IPaginationList<IOrganizationFloor>;
	organizationBuildingCreatedBies?: IPaginationList<IOrganizationBuilding>;
	organizationBuildingUpdatedBies?: IPaginationList<IOrganizationBuilding>;
	roomTypeFloorCreatedBies?: IPaginationList<IRoomTypeFloor>;
	roomTypeFloorUpdatedBies?: IPaginationList<IRoomTypeFloor>;
	roomTypeBuildingCreatedBies?: IPaginationList<IRoomTypeBuilding>;
	roomTypeBuildingUpdatedBies?: IPaginationList<IRoomTypeBuilding>;
	itemToPersonCreatedBies?: IPaginationList<IItemToPerson>;
	itemToPersonUpdatedBies?: IPaginationList<IItemToPerson>;
	personToBuildingCreatedBies?: IPaginationList<IPersonToBuilding>;
	personToBuildingUpdatedBies?: IPaginationList<IPersonToBuilding>;
	dimensionToPersonCreatedBies?: IPaginationList<IDimensionToPerson>;
	dimensionToPersonUpdatedBies?: IPaginationList<IDimensionToPerson>;
	dimensionTypeToBuildingCreatedBies?: IPaginationList<IDimensionTypeToBuilding>;
	dimensionTypeToBuildingUpdatedBies?: IPaginationList<IDimensionTypeToBuilding>;
	personWorkingLocationCreatedBies?: IPaginationList<IPersonWorkingLocation>;
	personWorkingLocationUpdatedBies?: IPaginationList<IPersonWorkingLocation>;
	personToWorkplaceBookingCreatedBies?: IPaginationList<IPersonToWorkplaceBooking>;
	personToWorkplaceBookingUpdatedBies?: IPaginationList<IPersonToWorkplaceBooking>;
	personToRoomBookingCreatedBies?: IPaginationList<IPersonToRoomBooking>;
	personToRoomBookingUpdatedBies?: IPaginationList<IPersonToRoomBooking>;
	personToDimensionBookingCreatedBies?: IPaginationList<IPersonToDimensionBooking>;
	personToDimensionBookingUpdatedBies?: IPaginationList<IPersonToDimensionBooking>;
	personCompanyToItemTypeCreatedBies?: IPaginationList<IPersonCompanyToItemType>;
	personCompanyToItemTypeUpdatedBies?: IPaginationList<IPersonCompanyToItemType>;
	personCompanyToRoomTypeCreatedBies?: IPaginationList<IPersonCompanyToRoomType>;
	personCompanyToRoomTypeUpdatedBies?: IPaginationList<IPersonCompanyToRoomType>;
	personCompanyToItemCreatedBies?: IPaginationList<IPersonCompanyToItem>;
	personCompanyToItemUpdatedBies?: IPaginationList<IPersonCompanyToItem>;
	legendCreatedBies?: IPaginationList<ILegend>;
	legendUpdatedBies?: IPaginationList<ILegend>;
	openerPostMessageHostCreatedBies?: IPaginationList<IOpenerPostMessageHost>;
	openerPostMessageHostUpdatedBies?: IPaginationList<IOpenerPostMessageHost>;
	companyWorkingLocationCreatedBies?: IPaginationList<ICompanyWorkingLocation>;
	companyWorkingLocationUpdatedBies?: IPaginationList<ICompanyWorkingLocation>;
	bookingVehicleConfigurationCreatedBies?: IPaginationList<IBookingVehicleConfiguration>;
	bookingVehicleConfigurationUpdatedBies?: IPaginationList<IBookingVehicleConfiguration>;
	bookingVehicleConfigurationToParkingRoomTypeConfigurationCreatedBies?: IPaginationList<IBookingVehicleConfigurationToParkingRoomTypeConfiguration>;
	bookingVehicleConfigurationToParkingRoomTypeConfigurationUpdatedBies?: IPaginationList<IBookingVehicleConfigurationToParkingRoomTypeConfiguration>;
	contentRoleCreatedBies?: IPaginationList<IContentRole>;
	contentRoleUpdatedBies?: IPaginationList<IContentRole>;
	jupUserCompanyToJupRoles?: IPaginationList<IJupUserCompanyToJupRole>;
	jupUserCompanyToJupRoleCreatedBies?: IPaginationList<IJupUserCompanyToJupRole>;
	jupUserCompanyToJupRoleUpdatedBies?: IPaginationList<IJupUserCompanyToJupRole>;
	contentRoleToBuildingCreatedBies?: IPaginationList<IContentRoleToBuilding>;
	contentRoleToBuildingUpdatedBies?: IPaginationList<IContentRoleToBuilding>;
	contentRoleToUserCompanies?: IPaginationList<IContentRoleToUserCompany>;
	contentRoleToUserCompanyCreatedBies?: IPaginationList<IContentRoleToUserCompany>;
	contentRoleToUserCompanyUpdatedBies?: IPaginationList<IContentRoleToUserCompany>;
	contentRoleToFloorCreatedBies?: IPaginationList<IContentRoleToFloor>;
	contentRoleToFloorUpdatedBies?: IPaginationList<IContentRoleToFloor>;
	partnerApiCredentialCreatedBies?: IPaginationList<IPartnerApiCredential>;
	partnerApiCredentialUpdatedBies?: IPaginationList<IPartnerApiCredential>;
	apiUserCreatedBies?: IPaginationList<IApiUser>;
	apiUserUpdatedBies?: IPaginationList<IApiUser>;
	apiUserToJupRoleCreatedBies?: IPaginationList<IApiUserToJupRole>;
	apiUserToJupRoleUpdatedBies?: IPaginationList<IApiUserToJupRole>;
	apiUserToContentRoleCreatedBies?: IPaginationList<IApiUserToContentRole>;
	apiUserToContentRoleUpdatedBies?: IPaginationList<IApiUserToContentRole>;
	jupUiTenantOperationCreatedBies?: IPaginationList<IJupUiTenantOperation>;
	jupUiTenantOperationUpdatedBies?: IPaginationList<IJupUiTenantOperation>;
	contentRoleToJupUiTenantOperationCreatedBies?: IPaginationList<IContentRoleToJupUiTenantOperation>;
	contentRoleToJupUiTenantOperationUpdatedBies?: IPaginationList<IContentRoleToJupUiTenantOperation>;
	userRegistrationTenantRuleCreatedBies?: IPaginationList<IUserRegistrationTenantRule>;
	userRegistrationTenantRuleUpdatedBies?: IPaginationList<IUserRegistrationTenantRule>;
	userRegistrationTenantRuleToJupRoleCreatedBies?: IPaginationList<IUserRegistrationTenantRuleToJupRole>;
	userRegistrationTenantRuleToJupRoleUpdatedBies?: IPaginationList<IUserRegistrationTenantRuleToJupRole>;
	userRegistrationTenantRuleToContentRoleCreatedBies?: IPaginationList<IUserRegistrationTenantRuleToContentRole>;
	userRegistrationTenantRuleToContentRoleUpdatedBies?: IPaginationList<IUserRegistrationTenantRuleToContentRole>;
	partnerExportMappingConfigurationCreatedBies?: IPaginationList<IPartnerExportMappingConfiguration>;
	partnerExportMappingConfigurationUpdatedBies?: IPaginationList<IPartnerExportMappingConfiguration>;
	partnerExportMappingCreatedBies?: IPaginationList<IPartnerExportMapping>;
	partnerExportMappingUpdatedBies?: IPaginationList<IPartnerExportMapping>;
	partnerExportMappingToRoomTypeCreatedBies?: IPaginationList<IPartnerExportMappingToRoomType>;
	partnerExportMappingToRoomTypeUpdatedBies?: IPaginationList<IPartnerExportMappingToRoomType>;
	partnerExportMappingConfigurationToFloorCreatedBies?: IPaginationList<IPartnerExportMappingConfigurationToFloor>;
	partnerExportMappingConfigurationToFloorUpdatedBies?: IPaginationList<IPartnerExportMappingConfigurationToFloor>;
	itemFactCreatedBies?: IPaginationList<IItemFact>;
	itemFactUpdatedBies?: IPaginationList<IItemFact>;
	featureFamilyCreatedBies?: IPaginationList<IFeatureFamily>;
	featureFamilyUpdatedBies?: IPaginationList<IFeatureFamily>;
	featureGroupCreatedBies?: IPaginationList<IFeatureGroup>;
	featureGroupUpdatedBies?: IPaginationList<IFeatureGroup>;
	featureCreatedBies?: IPaginationList<IFeature>;
	featureUpdatedBies?: IPaginationList<IFeature>;
}
export interface ICompanyWorkingLocationRaw extends IEntity {
	id: number;
	label?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	companyId: number;
	workingLocationId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
}
export interface ICompanyWorkingLocation extends ICompanyWorkingLocationRaw {
	company?: ICompany;
	workingLocation?: IWorkingLocation;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
}
export interface ICompanyRaw extends IEntity {
	id: number;
	name: string;
	prettyName?: string;
	logoPath?: IJupImage;
	iconPath?: IJupImage;
	proxyImages?: boolean;
	workingDaysCount?: number;
	enablePathfinding?: boolean;
	planningNumberOfDays?: number;
	enableCrowdedDimensionForBooking?: boolean;
	enableBuildingBookingWhenAllDimensionsAreCrowded?: boolean;
	enableStaticDeskReleaseOnAbsence?: boolean;
	workplaceBookingConfirmationRange?: string;
	workplaceBookingAgendaSyncEnabled?: boolean;
	trackUserActivity?: boolean;
	jwtClaimCode?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	companyTypeId?: number | null;
}
export interface ICompany extends ICompanyRaw {
	companyType?: ICompanyType;
	userCompanies?: IPaginationList<IUserCompany>;
	buildingTypes?: IPaginationList<IBuildingType>;
	buildings?: IPaginationList<IBuilding>;
	companyWorkingLocations?: IPaginationList<ICompanyWorkingLocation>;
}
export interface IBuildingTypeRaw extends IEntity {
	id: number;
	name: string;
	code?: string;
	color?: string;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	companyId: number;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
}
export interface IBuildingType extends IBuildingTypeRaw {
	company?: ICompany;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	buildings?: IPaginationList<IBuilding>;
}
export interface IBuildingRaw extends IEntity {
	id: number;
	name: string;
	color: string;
	surface?: number;
	leaseStartDate?: string;
	leaseEndDate?: string;
	purchaseDate?: string;
	documents?: string;
	picture?: IJupImage;
	regulatoryCapacity?: number;
	parkingSpaceCount?: number;
	constructionYear?: number;
	yearlyCondominiumFees?: number;
	yearlyRent?: number;
	yearlyParkingRent?: number;
	yearlyTaxFees?: number;
	yearlyExploitationFees?: number;
	rentReferenceIndex?: number;
	securityDeposit?: number;
	code?: string;
	roomsArea?: number;
	roomsCount?: number;
	workplacesCount?: number;
	workplacesRatio?: number;
	peopleCount?: number;
	seatsCount?: number;
	peopleRatio?: number;
	occupancyRate?: number;
	expansionRatio?: number;
	freeWorkplacesCount?: number;
	flexWorkplacesCount?: number;
	sharedWorkplacesCount?: number;
	sharedWorkplacesRatio?: number;
	transitWorkplacesCount?: number;
	flexRatio?: number;
	seatsPeopleRatio?: number;
	totalPeopleCount?: number;
	carbonFootprint?: number;
	totalCapacityCount?: number;
	totalCapacityWorkplaceCountRatio?: number;
	dimensionPeopleCount?: number;
	address?: IJupAddress;
	createdAt?: string;
	updatedAt?: string;
	externalId?: string;
	companyId: number;
	buildingTypeId?: number | null;
	userCompanyOwnerId?: number | null;
	jupUiLayoutId?: number | null;
	campusId?: number | null;
	buildingId?: number | null;
	userCompanyCreatedById?: number | null;
	userCompanyUpdatedById?: number | null;
}
export interface IBuilding extends IBuildingRaw {
	company?: ICompany;
	buildingType?: IBuildingType;
	userCompanyOwner?: IUserCompany;
	jupUiLayout?: IJupUiLayout;
	campus?: ICampus;
	building?: IBuilding;
	userCompanyCreatedBy?: IUserCompany;
	userCompanyUpdatedBy?: IUserCompany;
	buildings?: IPaginationList<IBuilding>;
	floors?: IPaginationList<IFloor>;
	roomTypeGroupBuildings?: IPaginationList<IRoomTypeGroupBuilding>;
	costCenterBuildings?: IPaginationList<ICostCenterBuilding>;
	dimensionBuildings?: IPaginationList<IDimensionBuilding>;
	facts?: IPaginationList<IFact>;
	organizationBuildings?: IPaginationList<IOrganizationBuilding>;
	roomTypeBuildings?: IPaginationList<IRoomTypeBuilding>;
	personToBuildings?: IPaginationList<IPersonToBuilding>;
	dimensionTypeToBuildings?: IPaginationList<IDimensionTypeToBuilding>;
	contentRoleToBuildings?: IPaginationList<IContentRoleToBuilding>;
}
/** Minimal QueryNode shape for Surfy `POST /api/v1/data/entities` (isomorphic). */
export type SurfyWhereOperator = "like" | "eq" | "in" | "notIn" | "notEq" | "is";
export type SurfyFilterValue = string | number | boolean | null | readonly (string | number)[];
export interface SurfyQueryFilter<Column extends string = string> {
	readonly operator: SurfyWhereOperator;
	readonly column: Column;
	readonly value: SurfyFilterValue;
}
export interface SurfyQueryNodePagination {
	readonly limit: number;
	readonly offset?: number;
}
export type SurfyObjectTypeName = "building" | "floor" | "room" | (string & {});
export type SurfyQueryTreeNode = string | SurfyQueryNode;
export interface SurfyQueryNode<Name extends SurfyObjectTypeName = SurfyObjectTypeName> {
	readonly name: Name;
	readonly _?: readonly SurfyQueryTreeNode[];
	readonly filters?: readonly SurfyQueryFilter[];
	readonly pagination?: SurfyQueryNodePagination;
	readonly order?: string;
	readonly required?: boolean;
	readonly totalCount?: boolean;
}
/** Typed QueryNodes for common object-type names (not entity DTOs). */
export type SurfyBuildingQueryNode = SurfyQueryNode<"building">;
export type SurfyFloorQueryNode = SurfyQueryNode<"floor">;
export type SurfyRoomQueryNode = SurfyQueryNode<"room">;
export interface SurfyEntitiesResponse<T> {
	readonly entities?: readonly T[];
	readonly totalCount?: number;
}
export declare function createFilter<Column extends string>(operator: SurfyWhereOperator, column: Column, value: SurfyFilterValue): SurfyQueryFilter<Column>;
export declare function normalizeSurfyBaseUrl(baseUrl: string): string;
export type SurfyRequestAuth = {
	readonly baseUrl: string;
	readonly tenant: string;
	readonly getAccessToken: () => Promise<string>;
	readonly locale?: string;
	/**
	 * Forbidden — machine JWT via {@link SurfyRequestAuth.getAccessToken} only.
	 * Present as `never` so TypeScript rejects integrator mistakes at compile time.
	 */
	readonly clientSecret?: never;
};
export type SurfyHttpError = Error & {
	readonly status: number;
	readonly code: SurfySdkErrorCode;
};
export declare function buildSurfyApiHeaders(auth: SurfyRequestAuth): Promise<HeadersInit>;
/** Map HTTP status to public SDK error codes (401 auth / 403 entitlement). */
export declare function mapHttpStatusToSurfySdkErrorCode(status: number): SurfySdkErrorCode;
export declare function createSurfyHttpError(message: string, status: number, code?: "AUTH_EXPIRED" | "AUTH_FORBIDDEN" | "TENANT_MISMATCH" | "LAYOUT_NOT_FOUND" | "NETWORK" | "SDK_CONFIG" | "PIN_GPS_UNAVAILABLE"): SurfyHttpError;
export declare function mapSurfyHttpErrorToDetail(error: unknown, fallbackMessage?: string): SurfySdkErrorDetail;
/**
 * Isomorphic Surfy HTTP helper — uses `globalThis.fetch` only (browser + Node 18+).
 * Does not touch `window` / `document`.
 */
export declare function surfyFetchJson<T>(auth: SurfyRequestAuth, path: string, init?: {
	readonly method?: string;
	readonly body?: unknown;
	readonly signal?: AbortSignal;
}): Promise<T>;
export declare const SURFY_ENTITIES_ROUTE = "/api/v1/data/entities";
export type SurfyClientOptions = SurfyRequestAuth;
/**
 * Isomorphic Surfy data client — inject `baseUrl` (origin) at creation.
 * Primary API: {@link SurfyClient.fetchEntities} with your own QueryNode
 * (business queries stay in the app, not in the SDK).
 */
export declare class SurfyClient {
	private readonly auth;
	private constructor();
	static create(options: SurfyClientOptions): SurfyClient;
	get baseUrl(): string;
	get tenant(): string;
	/**
	 * POST `/api/v1/data/entities` — pass any QueryNode you build in app code.
	 */
	fetchEntities<T>(queryNode: SurfyQueryNode, signal?: AbortSignal): Promise<T[]>;
}

export {};
