// Generated by dts-bundle-generator v9.5.1

/** Stable subset of layout payload used by the embed renderer (phase 1b). */
export interface IEmbedRoomPoint {
	readonly id: number;
	readonly x: number;
	readonly y: number;
}
export interface IEmbedRoomPointRoom {
	readonly roomPointId: number;
	readonly sortIndex?: number;
	readonly roomPoint?: IEmbedRoomPoint;
}
export interface IEmbedRoom {
	readonly id: number;
	readonly name?: string;
	readonly roomPointRooms?: {
		readonly nodes?: readonly IEmbedRoomPointRoom[];
	};
}
export interface IEmbedLayoutViewData {
	readonly rooms: readonly IEmbedRoom[];
	readonly roomPoints: readonly IEmbedRoomPoint[];
}
export type SurfySdkErrorCode = "AUTH_EXPIRED" | "AUTH_FORBIDDEN" | "TENANT_MISMATCH" | "LAYOUT_NOT_FOUND" | "NETWORK" | "SDK_CONFIG";
export interface SurfySdkErrorDetail {
	readonly code: SurfySdkErrorCode;
	readonly message: string;
}
/** Shared imperative API for all layout Web Components (2D + 3D). */
export interface SurfyLayoutElement extends HTMLElement {
	setAccessTokenProvider(provider: () => Promise<string>): void;
	setRoomColors(colors: Record<number, string>): void;
	clearRoomColors(): void;
}
export interface SurfyFloorLayout2dReadyDetail {
	readonly floorId: number;
}
export interface SurfyFloorLayout3dReadyDetail {
	readonly floorId: number;
}
export interface SurfyBuildingLayout3dReadyDetail {
	readonly buildingId: number;
}
/**
 * @deprecated Use {@link SurfyFloorLayout2dReadyDetail}.
 */
export type SurfyFloorPlanReadyDetail = SurfyFloorLayout2dReadyDetail;
export interface SurfyRoomSelectedDetail {
	readonly roomId: number;
	readonly name: string;
}
export type SurfyRoomHoverDetail = SurfyRoomSelectedDetail | null;
/** Phase 2 — options merged imperatively. */
export interface SurfyFloorPlanOptions {
	readonly showLegend?: boolean;
	readonly locale?: string;
}
/** @deprecated Use {@link SurfyLayoutElement}. */
export type SurfyFloorPlanElement = SurfyLayoutElement;
export type SurfyFloorLayout2dElement = SurfyLayoutElement;
export type SurfyFloorLayout3dElement = SurfyLayoutElement;
export type SurfyBuildingLayout3dElement = SurfyLayoutElement;
export interface IFetchBuildingLayoutParams {
	readonly baseUrl: string;
	readonly tenant: string;
	readonly buildingId: number;
	readonly getAccessToken: () => Promise<string>;
	readonly locale?: string;
	readonly signal?: AbortSignal;
}
export declare function fetchBuildingLayoutData(params: IFetchBuildingLayoutParams): Promise<IEmbedLayoutViewData>;
export interface IFetchFloorLayoutParams {
	readonly baseUrl: string;
	readonly tenant: string;
	readonly floorId: number;
	readonly getAccessToken: () => Promise<string>;
	readonly locale?: string;
	readonly signal?: AbortSignal;
}
export declare function fetchFloorLayoutData(params: IFetchFloorLayoutParams): Promise<IEmbedLayoutViewData>;
/** Published SDK semver — bump on public API changes. */
export declare const SURFY_SDK_VERSION = "0.1.0";
/** 2D floor layout Web Component (phase 1b). */
export declare const SURFY_FLOOR_LAYOUT_2D_TAG = "surfy-floor-layout-2d";
/** 3D floor layout Web Component — CubyV2 (phase 2). */
export declare const SURFY_FLOOR_LAYOUT_3D_TAG = "surfy-floor-layout-3d";
/** 3D building layout Web Component — CubyV2 (phase 2). */
export declare const SURFY_BUILDING_LAYOUT_3D_TAG = "surfy-building-layout-3d";
/**
 * @deprecated Use {@link SURFY_FLOOR_LAYOUT_2D_TAG}.
 */
export declare const SURFY_FLOOR_PLAN_TAG = "surfy-floor-plan";
/** Registers layout Web Components (`surfy-floor-layout-2d`, `surfy-building-layout-3d`, deprecated `surfy-floor-plan`). */
export declare function registerSurfyLayoutElements(): void;
/** @deprecated Use {@link registerSurfyLayoutElements}. */
export declare function registerSurfyFloorPlanElement(): void;

export {};
