// Generated by dts-bundle-generator v9.5.1

import { CSSProperties, ReactElement, ReactNode } from 'react';

/** Opaque jotai store handle — runtime from `jotai` createStore. */
export type SurfySdkJotaiStore = {
	readonly get: (atom: unknown) => unknown;
	readonly set: (atom: unknown, value: unknown) => void;
};
export interface ISurfySdkReactProviderProps {
	readonly children: ReactNode;
	readonly store?: SurfySdkJotaiStore;
}
export interface ISurfyFloorLayout2dReactProps {
	readonly floorId: number;
	readonly tenant: string;
	readonly baseUrl: string;
	readonly getAccessToken: () => Promise<string>;
	readonly instanceId?: string;
	readonly layoutData?: unknown;
	readonly fillParent?: boolean;
	readonly wrapProvider?: boolean;
	readonly skipMasterDataPrepare?: boolean;
	readonly style?: CSSProperties;
	readonly className?: string;
	readonly onReady?: () => void;
	readonly onError?: (detail: unknown) => void;
	readonly children?: ReactNode;
}
export interface ISurfyBuildingLayout3dReactProps {
	readonly buildingId: number;
	readonly tenant: string;
	readonly baseUrl: string;
	readonly getAccessToken: () => Promise<string>;
	readonly instanceId?: string;
	readonly layoutData?: unknown;
	readonly fillParent?: boolean;
	readonly wrapProvider?: boolean;
	readonly skipMasterDataPrepare?: boolean;
	readonly style?: CSSProperties;
	readonly className?: string;
	readonly onReady?: () => void;
	readonly onError?: (detail: unknown) => void;
	readonly children?: ReactNode;
}
export interface ISurfyFloorLayout3dReactProps {
	readonly floorId: number;
	readonly buildingId?: number;
	readonly tenant: string;
	readonly baseUrl: string;
	readonly getAccessToken: () => Promise<string>;
	readonly instanceId?: string;
	readonly layoutData?: unknown;
	readonly fillParent?: boolean;
	readonly wrapProvider?: boolean;
	readonly skipMasterDataPrepare?: boolean;
	readonly style?: CSSProperties;
	readonly className?: string;
	readonly onReady?: () => void;
	readonly onError?: (detail: unknown) => void;
	readonly children?: ReactNode;
}
export interface ISimpleFloorPlanRootProps {
	readonly children?: ReactNode;
	readonly [key: string]: unknown;
}
export interface ISimpleBuildingPlanRootProps {
	readonly children?: ReactNode;
	readonly [key: string]: unknown;
}
export declare function SurfySdkReactProvider(props: ISurfySdkReactProviderProps): ReactElement;
export declare function SurfyFloorLayout2dReact(props: ISurfyFloorLayout2dReactProps): ReactElement;
export declare function SurfyBuildingLayout3dReact(props: ISurfyBuildingLayout3dReactProps): ReactElement;
export declare function SurfyFloorLayout3dReact(props: ISurfyFloorLayout3dReactProps): ReactElement;
export declare function SimpleFloorPlanRoot(props: ISimpleFloorPlanRootProps): ReactElement;
export declare function SimpleBuildingPlanRoot(props: ISimpleBuildingPlanRootProps): ReactElement;
export declare function useSurfySdkStore(): SurfySdkJotaiStore;
export declare function useSurfySdkStoreOptional(): SurfySdkJotaiStore | null;
export declare function useRoom(roomId: number): unknown;
export declare function useRoomValue(roomId: number): unknown;
export declare function useRooms(workCanvasId: string): unknown;
export declare function useSetRoom(): (roomId: number, room: unknown) => void;
export declare function setRoomInSurfySdkStore(store: SurfySdkJotaiStore, roomId: number, room: unknown): void;

export {};
